### ISSUE TITLE
Make a Declaration Nunjucks argument link broken

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#107]
Describe the bug
Nunjucks macro arguments link is broken

To Reproduce
Checkout add declaration branch and go to http://localhost:3000/patterns/make-a-declaration and select the nunjucks tab.

Expected behaviour
Link goes somewhere meaningful or isn't required

**Comment by simoneduca** [comment]
Thanks. The issue affects all examples. I'll remove the links as there's no use case for it atm.
