### ISSUE TITLE
HTML space format (text decoration page)

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#112]
## Describe the issue
Html code example on the page isn't keeping the tabbing/indenting of code, to follow GDS' style

## Steps to reproduce the issue
NA

## Actual vs expected behaviour
The pre code should look similar to GDS' https://design-system.service.gov.uk/components/date-input/

## Environment (where applicable)
NA

- Operating system:
- Browser:
- Browser version:

**Comment by simoneduca** [comment]
https://github.com/alphagov/govuk-frontend/pull/1353/files

**Comment by abbott567** [comment]
I've had this problem and I worked out that it's the Nunjucks Markdown package itself. It seems that when you pass in markdown between the `{% markdown %` tags this is what causes the white space to be stripped out.

I've found two ways around it, one is to use a custom filter the other is to not rely on the Nunjucks Markdown package. 

## Example 1: Use an override function and custom formatting

I wrote a MarkedJS override function which used a double tilde to denote the white space:

```javascript
function code (renderer) {
  renderer.code = function (code, infostring, escaped) {
    const lang = (infostring || '').match(/\S*/)[0]
    if (this.options.highlight) {
      const out = this.options.highlight(code, lang)
      if (out != null && out !== code) {
        escaped = true
        code = out
      }
    }
    code = code.replace(/~~/g, '')
    if (!lang) return `<pre><code role="figure" tabindex="0" class="hljs">${code}</code></pre>\n`
    return `<pre><code role="figure" tabindex="0" class="hljs ${this.options.langPrefix}${escape(lang, true)}">${code}</code></pre>\n`
  }
}
```
Using this method, you can still use the Nunjucks Markdown package but you add a double tilde to the start of your code examples to fire the filter and reset the whitespace. For example:

````html
```html
~~<div>
~~  <p>
~~    ...
~~  </p>
~~</div>
```
````

## Example 2: Don't use the Nunjucks Markdown package

Just remove the package and use a regular Nunjucks filter to render anything which is markdown. For example:
```javascript
// Add a filter
const marked = require('marked')
nunjucksEnvironment.addFilter('markdown', marked)
```

```javascript
// Call the filter
{% set markdowndContent %}{% include './path-to-markdown/content.md' %}{% endset %}
{{markdownContent|markdown|safe}}
```

Hope this helps.

**Comment by htmlandbacon** [comment]
HTML now has a consistent view due to work done else where, nunjucks render is now also rendering as consistent depending on the example components have been reviewed and changed.
