### ISSUE TITLE
Update the copy for users who have been timed out but are not signed in to a service

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#127]
## What

Update the copy for users who have been timed out but are not signed in to a service

## Why
For clarity and encompass services that aren't applications for something.

## Done when

Change content from
<img width="857" alt="Screen Shot 2021-04-29 at 13 53 56" src="https://user-images.githubusercontent.com/57486301/116553856-7ac1b800-a8f2-11eb-8630-c77853bb284c.png">

 
to

Your answers have been deleted

We have deleted your answers because you did not do anything for 20 minutes. This is to protect your information.
You will need to start again.

Start again

(Countdown to 0 for the 2 minutes)

**Comment by michaelcattell** [comment]
Content updated
