### ISSUE TITLE
Decide if design system needs a tag for agent-facing designs and design if required

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#128]
## What
Decide if we need a flag for designs that have only been used on agent-facing services.

## Why

As we expand the design system and include components that are currently only used on agent-facing services we need to decide if we need a tag/flag for agent-facing designs so it is easy for users of the design system to identify them.

## Done when

- [x] Decision made on whether it's needed
- [ ] Design for tag/flag if required

**Comment by michaelcattell** [comment]
Planning a mini-workshop about this ticket to work through the solution via mural (if/when access is granted).

**Comment by jonhurrell** [comment]
Interesting discussion from the X-Gov task list workshop today. People find the different between components/patterns confusing. In using our design system do they need to know the difference or could we be bold/lazy and break down the vernacular to 'here the thing's you can use to design your services [show the things in the simplest way]'

**Comment by michaelcattell** [comment]
Discussion within the team and decision made to park this ticket (not needed) so moving to done
