### ISSUE TITLE
Review design of timeline component

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#129]
## What

Review design of timeline component

## Why

Review the existing design for the timeline and update if required.

**Comment by michaelcattell** [comment]
Uploaded designs to #131 as I'll follow up with these examples with questions around the number of items shown at once etc
Once answered, I'll revisit this page to compare existing design to "real-world" examples.

**Comment by michaelcattell** [comment]
Discussed with team to duplicate what was on 'examples' page, so the visuals of the timeline to flow like:

Header of task
by nameofperson 
date
 Link text  (if needed to another page)
 
 Branch 'timeline' updated with layout

**Comment by jonhurrell** [comment]
Discussion captured in other tickets.
