### ISSUE TITLE
Build timeline page for design system

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#130]
## What
Build timeline page for design system - waiting for updated content

## Related stories
https://github.com/dwp/design-system/issues/99

**Comment by michaelcattell** [comment]
Uploaded designs to https://github.com/dwp/design-system/issues/131 as i'll follow up with these examples with questions around amount of items shown at once etc

**Comment by HelenOsg** [comment]
@michaelcattell The page has been created in the patterns section but this is a component so needs to be moved under there

**Comment by michaelcattell** [comment]
Thanks to Simone, the changes have been made and now the item is in components

**Comment by HelenOsg** [comment]
@michaelcattell I can see the timeline in the side nav in components now but when i click on it it takes me through to a timeline page in the pattern section of the site.

**Comment by michaelcattell** [comment]
Amended to fix above, but also noticed the URL reverts to patterns/timeline instead of comonents/timeline - might be a @simoneduca fix?

**Comment by michaelcattell** [comment]
Ignore the above request - updated subnav and fixed the URL issue. Pushed to branch 'timeline'
