### ISSUE TITLE
Outreach to design community for examples of numbers of items shown in timeline

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#131]
## What
Outreach to design community for examples of numbers of items shown in timeline 

## Why
To give guidance on the number of items shown in the timeline and how to handle more items than recommended. 

## Outcomes

Improving existing design and guidance documentation

## Related stories
https://github.com/dwp/design-system/issues/99

**Comment by michaelcattell** [comment]
Reached out to the design community and they shared screen grabs.
Will reach out to them one by one and ask them about "situational" solutions (like the "what happens if you have a lot of items in your timeline" and any feedback they have)

**Comment by michaelcattell** [comment]
![Screenshot 2021-05-04 at 13 53 22](https://user-images.githubusercontent.com/52162960/117306713-d6062400-ae77-11eb-81dc-6f773fae9d0a.png)
(Allan)

**Comment by michaelcattell** [comment]
![Searchlight_Apply_for_a_NINo_application_history](https://user-images.githubusercontent.com/52162960/117306808-eae2b780-ae77-11eb-82d0-7b63c950b9ff.jpg)
![Searchlight_benefits_deatails_key_dates](https://user-images.githubusercontent.com/52162960/117306812-ec13e480-ae77-11eb-9187-49b03e851ddb.jpg)
Jon Ha.

**Benefits timeline**, live now, before my time on Searchlight so don’t have any more info other than it’s there and in use.

**Apply for a NINo**, Application History - currently in development, design based on the timeline component from DWP Design Examples. Tested well with agents in multiple rounds of testing between Dec 2020 - April 2021.
Agents didn’t reference the component specifically when asked to think aloud. When prompted they understood there was previous activity associated with an application and they could clearly see what it was in the Application History.

**Comment by michaelcattell** [comment]
![smi-example](https://user-images.githubusercontent.com/52162960/117306930-08b01c80-ae78-11eb-80dd-2a66a183c33a.jpg)
Becky M 

They’d designed it to auto-populate notes from status changes the agents completed. Agents could also add specific notes. This was useful for other agents who had access to the account. It was also for audit trail purposes as the changes were linked to the agent account and listed who had made the change/added the note.

**Comment by michaelcattell** [comment]
![M2UC](https://user-images.githubusercontent.com/52162960/117309671-8b39db80-ae7a-11eb-84b0-17ff264bc630.png)
Sam

This would show 4 items and then expand (upon clicking view full history) and it shows all of the history on the page
