### ISSUE TITLE
Retire Consent to Cookies

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#142]
## What
Add notification banner to the documentation alerting people too use the GDS Design System pattern

## Why
The issues we have with the previous pattern proposed (didn't meet our CIO requirements) have been resolved.

## Done when

- [x] Update documentation with notification to use the GDS pattern
- [x] Change phase banner to retired

**Comment by jonhurrell** [comment]
@HelenOsg Can you update this ticket once the content is ready.

**Comment by HelenOsg** [comment]
@jonhurrell 

For the banner 'This pattern has been replaced by the <cookie page pattern> and <cookie banner> on the GDS Design System.'

Replace top sentence with

This pattern has been replaced by the <cookie page pattern> and <cookie banner> on the GDS Design System and should not be used.  This is because the GDS pattern now meets the requirements set out by the DWP Chief Information Officer.

Link for Cookie banner https://design-system.service.gov.uk/components/cookie-banner/
Cookie page pattern https://design-system.service.gov.uk/patterns/cookies-page/

**Comment by jonhurrell** [comment]
@HelenOsg I've used the above and tweaked the copy a little due to layout (opening with retire sentence underneath the phase banner, then notification). Have a look on the retire-cookies branch.

**Comment by HelenOsg** [comment]
The content look's a bit repetitive. Should we just remove the top sentence and have the info in the banner? @jonhurrell

**Comment by jonhurrell** [comment]
I think the opening paragraph is to explain the retired status, then the notification is to warn using again. Feels ok to me, but happy to try other options.

**Comment by HelenOsg** [comment]
Fair point. Would be good to get it live and then get some feedback on it so we can include it in the sunset process.

**Comment by jonhurrell** [comment]
Can leave it for tomorrow for @michaelcattell to review or ask @simoneduca to push live.

**Comment by HelenOsg** [comment]
I'm not sure if the added info looks better in the top sentence or in the banner? The top sentence might get ignored but could be too much in the banner.
<img width="802" alt="Screen Shot 2021-05-13 at 14 01 12" src="https://user-images.githubusercontent.com/57486301/118129304-ebd59500-b3f3-11eb-9f24-3e1d9d8e53fa.png">
<img width="823" alt="Screen Shot 2021-05-13 at 14 02 03" src="https://user-images.githubusercontent.com/57486301/118129307-ec6e2b80-b3f3-11eb-9edb-751842bf148c.png">

**Comment by jonhurrell** [comment]
New paragraph to give the message balance.

<img width="797" alt="Screen Shot 2021-05-14 at 08 24 49" src="https://user-images.githubusercontent.com/809482/118236599-2ab82900-b48e-11eb-8e4f-d6affd5a8954.png">

**Comment by michaelcattell** [comment]
Provided an update on styles with slack channel, and as 'notification banner' needs to be above the h1 (https://design-system.service.gov.uk/components/notification-banner/#how-it-works) as a team we decided wasn't the correct fix - from previous experience we are using:
https://design-system.service.gov.uk/components/warning-text/

**Comment by jonhurrell** [comment]
I think we are bending the purpose of the notification banner component, so let's use warning text.

<img width="797" alt="Screen Shot 2021-05-14 at 11 34 28" src="https://user-images.githubusercontent.com/809482/118258980-711a8180-b4a8-11eb-91c0-8371e24658a1.png">
