### ISSUE TITLE
Missing word in sentence of warning on cookie consent page

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#144]
## Describe the issue
grammatical error in the last sentence of the warning. It's missing the word is. It should read 'You do not need to update your service if it is already using this pattern.'

## Steps to reproduce the issue
Visit - https://design-system.dwp.gov.uk/patterns/consent-to-cookies

## Actual vs expected behaviour
Should read 'You do not need to update your service if it is already using this pattern.'

**Comment by simoneduca** [comment]
done
