### ISSUE TITLE
Update example in the manage session timeout pattern

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#145]
## Describe the issue
The content in the manage session timeout example doesn't reflect the updated version in the page. 

## Steps to reproduce the issue
View prototype page of manage session timeout and view example at top of page

## Actual vs expected behaviour
The example should use the content in the user is signed in example. Content can be found on the page.

**Comment by simoneduca** [comment]
@HelenOsg "The example should use the content in the user is signed in example". Why? I would expect the default would be not being signed-in.
