### ISSUE TITLE
Continue button on session timeout pattern wrong colour

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#153]
## Describe the issue
The continue button is showing yellow instead of green

## Steps to reproduce the issue
Visit the session pattern page

## Actual vs expected behaviour
Button should be green instead of yellow

<img width="997" alt="Screen Shot 2021-05-24 at 09 47 23" src="https://user-images.githubusercontent.com/57486301/119480321-7483f780-bd49-11eb-9164-ec566d2bae7c.png">

**Comment by simoneduca** [comment]
@HelenOsg I can't reproduce this, well not quite. I can see yellow flickering at first but then it's green. Which browser are you using? Have you tried clearing the browser cache?

**Comment by HelenOsg** [comment]
@simoneduca I get this on Chrome. When i move the cursor over the button it turns green with a yellow outline. Is that correct?
