### ISSUE TITLE
Review feedback from design community on design system site

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#201]
## What

Prior to publishing the updated Design System site we asked content and IxD designers to review the site and give feedback. The higher level suggestions need reviewing and a decision made on whether we implement them.

## Why

To ensure we meet user needs and to create engagement with the UCD community

## Outcomes

Review by 7 content designers resulted in the below feedback:
- Remove design research library (at least the list of links) until we’re clear how they work together.
- Change what’s new to latest updates and add time stamp for updates within the homepage box
- Make it clear when linking out to GitHub - how can we do this without it being clunky in tables??
- Bring the team page further up the navigation

**Comment by jonhurrell** [comment]
- [] Let's make the change from 'What's new' to 'Latest update' in nav and headings. Issue can be closed after changes.
