### ISSUE TITLE
Look at and improve steps "DONE WHEN" on all tickets

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#226]
## What
Improve the tick-list for the DONE WHEN on each new piece of work
## Why
Recently, the list has broken when going through the list, esp around Legal (not every ticket needs to be checked)
## Done when
When we have a more robust/generic version that works for more new tickets

**Comment by jonhurrell** [comment]
Close due to related https://github.com/dwp/design-system/issues/165
