### ISSUE TITLE
Navigation: Outreach to UCD community for examples and feedback on existing component

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#239]
Feedback from the working group (26/1/21):

**Primary navigation component**
HO ran through feedback consensus and comments
It was agreed that the design was not ready to be published on the design system and more work was required to further develop the component. 
Comments included that there was a lack of consistency in its use across services, research showing that is ignored/not used by agents and questions about whether the GDS primary nav solution could be used.
Next steps are to find more relevant examples of the component being used and investigate if the GDS primary nav in header solution could be used.

It was agreed that the example needed to show the primary navigation in context (perhaps to show with key details bar too).

Make it clear in guidance this if or internal services primary navigation and not to be used in citizen facing services when they should focus on the one page per thing.

CO – has there been mobile consideration – maybe not mobile but responsive as I’ve seen agents using it with browser that has been resized.

**_Agreed actions_**
-	Further examples required
-	Explore whether the GDS example can be/should be used

**Sub navigation**

HO ran through feedback consensus and comments
It was agreed that the design was ready to be published on the design system (after code refactoring and accessibility testing). 
Comments included checking if this had been tested for accessibility and users. It was also asked whether this should be grouped with the tabs component.
Next steps suggested included finding recent examples of it being used and user testing.

It was agreed that the guidance page should include recommendations on when to use the component and show examples in context. This included guidance on when to use a list of links for sub navigation and when to use the tabs. 

Wider discussion of how the sub navigation works with the tab component. Agreed that the two should be shown together but the tab component proposed should be the GDS one.

**_Agreed actions_**
-	Guidance page needs recreating

**Comment by michaelcattell** [comment]
Mock ups below:

Primary:
![image](https://user-images.githubusercontent.com/52162960/140747727-8de48286-b35d-4eaa-9c9b-cfdeab6ca339.png)

Sub:
![image](https://user-images.githubusercontent.com/52162960/140747741-3d678253-9296-40b3-96fc-5a5671436e3a.png)

**Comment by jonhurrell** [comment]
There's an example from the Agent Interface Workshop (Get your state Pension) that has a top level (global) nav example.

**Comment by jonhurrell** [comment]
Trying to source mobile examples.
