### ISSUE TITLE
Standardise and document our branching and release workflow

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#270]
## What
We need discuss and document a simple branching methodology for us all to work from.

## Why
To make things more consistent and easier to follow when we are collaborating within the codebase.

## Done when

- [x] Discussed options as a team
- [x] @simoneduca to walk through an example
- [x] Documented

## Outcomes
It will help productivity when we are all collaborating and onboard people faster. Less questions shoul

**Comment by simoneduca** [comment]
### Branching
After talking with @dtaylorbrown, we've settled on following a [simple Github flow](https://docs.github.com/en/get-started/quickstart/github-flow#following-github-flow) - applied to GitLab obviously - for the main site.
Af far as frontend, we will have more structure in place and I'll update that on Gitlab.

**Comment by simoneduca** [comment]
https://github.com/dwp/design-system/wiki
