### ISSUE TITLE
UI audit - feedback on implementing DWP front-end (styles)

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#278]
## Describe the issue
A comment was on content-design channel:
_Silly question maybe...
So the components that we have in this system use new classes, for example :
"dwp-key-details-bar__key-details"
How do we get these styles into our prototype kits? Do we need to manually add to the assets stylesheets, or is it all magically automated via integration with the GDS public assets?_

The issue is we have no instructions or "easy" way to get our styles(css) into our users prototype easily or all levels of knowledge.

## Steps to reproduce the issue
Using a "new" pattern like timeline, key details bar will not look or function how it should without css from DWP front-end

## Actual vs expected behaviour
Simply copy and pasting the pattern should show as intended within my prototype

## Environment (where applicable)
Using the GDS prototype as a framework, and making "DWP" prototypes

## Anything else
Should we think how people install the prototype - reason: 
- Knowledge of terminal could be minimal
- Speed, if we are promoting html prototypes speed should be a USP?
- Ease of use, it might feel easier to use an alternative - figma, sketch etc
- Is there an educational gap on how to run a prototype etc

## Linked to
https://github.com/dwp/design-system/issues/216 - Publish How to integrate DWP Design System components with CASA and GOVUK Prototype kit

**Comment by michaelcattell** [comment]
Discussions around possible solutions:
- include the css within the code solutions
- users install dwp-frontend
- instructions on how to install dwp-frontend use css 
Our removed example: https://gitlab.com/dwp/dwp-design-system/frontend/-/blob/main/README.md
MOJ example: https://design-patterns.service.justice.gov.uk/get-started/prototyping/)

**Comment by martinwake** [comment]
I think this can be closed. We have included CSS in the code examples and are working on guidance etc in other tickets.
