### ISSUE TITLE
Navigation: Discussion around use within Health (PIP)

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#289]
## What
A discussion with the IxDs within PIP team, (James A and Martin G) around what they have got so far, taking it forward and seeing if they can support the DS team. 

## Why
They are going through Alpha assessment and needing to get to the point of agreeing a build and realised it's in our backlog.
Why we accepted the meeting
- We have existing insights from (some) services to make recommendations from previous work-groups
- Priority set from previous work-group

### Research
- [x] Receive screen grabs from Martin G showing their potential use of primary, second and third navigation

### Promote
- [x] Show and tell back to IxD community if applicable

## Outcomes
- Martin, James to keep in the loop for future amends from testing
- They share amongst Health and wider if the pattern works
- They provide us with UR findings

## Who needs to know about this
UCD community
Design System team
Accessibility team

## Related stories
They used for inspiration:
(old)DWP examples: https://dwp-design-examples.herokuapp.com/example/navigation-global
(old)DWP examples: https://dwp-design-examples.herokuapp.com/example/navigation-secondary
Ministry of Justice Primary navigation pattern: https://design-patterns.service.justice.gov.uk/components/primary-navigation/
Ministry of Justice Secondary navigation pattern: https://design-patterns.service.justice.gov.uk/components/sub-navigation/
Ministry of Justice Side navigation pattern: https://design-patterns.service.justice.gov.uk/components/side-navigation/

## Anything else
- They ran an internal design crit and it was felt the primary navigation placement above the users data (key details bar) was jarring and possibly missed
- They got better design crit feedback using the secondary navigation underneath the key details bar so, as a team they are wanting to take that forward
- They have tested their designs with no direct feedback or mentioning of navigation
- They are planning to use the side navigation (fed from MOJ) on the left side when needed
- All their mock ups in desktop as internal agent, might need to cater for smaller screens
I recommended they use the Design Clinics (internally DWP) for more feedback on certain things like navigation, pattern usage etc

**Comment by michaelcattell** [comment]
Latest designs attached:
![PIP-Navigation-idea1](https://user-images.githubusercontent.com/52162960/142404378-109ce718-953d-4c21-8215-6c412ea3e3db.jpg)
![PIP-Navigation-idea2](https://user-images.githubusercontent.com/52162960/142404381-167e111d-51a3-46b5-8afd-bcbeee592fa4.jpg)
![PIP-Summary-page](https://user-images.githubusercontent.com/52162960/142404383-54671eff-9d89-42f6-a299-e50cfb52dc4e.jpg)

**Comment by michaelcattell** [comment]
Attended the design clinic (30th November), feedback from the group was:
Navigation felt a bigger issue, not just UI but the bigger picture (a lot of back and forth),
Key details bar needed to be kept consistent and more aligned to the DWP pattern https://design-system.dwp.gov.uk/components/key-details-bar
They were using full width of screen, instead of the recommended two-thirds from GDS design system https://design-system.service.gov.uk/styles/layout/#screen-size 

They will be testing the prototype soon - asked to be kept in the loop for feedback if navigation or key details are mentioned (and also keep an eye for when testing with their user-base if they "halved" the screen from other designers experience to support the two third feedback)

**Comment by jonhurrell** [comment]
Closed, and included into main [navigation epic ](https://github.com/dwp/design-system/issues/176)for reference.
