### ISSUE TITLE
Update GitHub repo with GitLab latest without config

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#315]
## Done when

- [ ] Thing to do

**Comment by simoneduca** [comment]
We need to agree what to do while we wait for the green light on the frontend module. As it stands, people without gitlab access can't run the project locally, which might put off some potential contributors. However, people could still submit PRs using the GUI (no need to run anything locally), _if_ they change something simple. That to me seems the more likely scenario - I can’t see people submitting a route refactor or the likes. So again, just including the static files seems enough. Wondering if I'm missing anything else.

**Comment by jonhurrell** [comment]
@simoneduca Can you move this to done once the readme has a node version added to it.
