### ISSUE TITLE
Key details bar: Track adoption and capture usage insights

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#318]
## What
A rolling ticket for the backlog to periodically check the key details usage and to capture any new insights to inform any iterative work.

## Why
The adoption is an important metric to the success so we can reduce the inconsistency of the component use.

## Done when
- [x] Capture feedback and additional insights within GitHub discussion to help inform any interaction going forward.
- [x] Log changes
- [x] Record any adoption by services
- [x] Review

## Current related stories
N/A

## Adopted by
- Health Assessment Service
- Personal Independence Payments Service

## Updates
- 25/07/22 feature: add govuk tag component
- 26/05/22 bug fix: HTML structure

**Comment by jonhurrell** [comment]
Health Assessment Service are using this.

**Comment by martinwake** [comment]
Research insights from Health Assessment Service: 

https://github.com/dwp/design-system-community-backlog/discussions/78#discussioncomment-3101693
