### ISSUE TITLE
Welsh toggle: Track adoption and capture usage insights

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#320]
## What
A rolling ticket for the backlog to periodically check the welsh toggle usage and to capture any new insights to inform any iterative work.

## Why
The adoption is an important metric to the success so we can reduce the inconsistency of the pattern use.

## Done when

- [ ] Record any adoption by services
- [ ] Capture feedback and additional insights within GitHub discussion to help inform any interaction going forward.
- [ ] Review

**Comment by martinwake** [comment]
https://github.com/dwp/design-system/issues/317#issue-1064776620

**Comment by martinwake** [comment]
Our pattern says "Do not put the Welsh language toggle in the footer" but this is a common pattern on gov.uk sites: would it be reasonable to allow this as an additional site for the link?

### Examples
gov.uk: 
![image](https://user-images.githubusercontent.com/26182217/176389406-a54fc9b6-f0ae-47ea-9e91-adb64410fb56.png)

Apply for a Passport:
![image](https://user-images.githubusercontent.com/26182217/176389597-4d36d2a7-1c4c-4079-ab86-a5b4d76baaf9.png)
