### ISSUE TITLE
Key details: API scope feedback

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#323]
## What
@htmlandbacon has some services in Health able to integrate the key details component, but there needs to be some refinement of the API scope and composability. 

[Feedback](https://github.com/dwp/design-system-community-backlog/discussions/78#discussioncomment-1743510)

## Why
We need to support the usage and iterate based on service context.

## Done when

- [x] Arrange a meeting with @htmlandbacon to discuss API changes and potential migration issues when updating components 

## Outcomes
A better component and service adoption.

**Comment by simoneduca** [comment]
Meeting set for Friday.
