### ISSUE TITLE
Session timeout example redirects to 404 after 10 seconds

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#326]
## Describe the issue
On the [Manage a session timeout](https://design-system.dwp.gov.uk/patterns/manage-a-session-timeout) pattern: following the first link titled "Open the example in a new window" shows a timeout warning including a 10-second countdown. After the countdown completes the "Page not found" (404) error displays.

## Steps to reproduce the issue
Visit https://design-system.dwp.gov.uk/patterns/manage-a-session-timeout and select the first link that reads "Open the example in a new window".

![image](https://user-images.githubusercontent.com/26182217/146803941-59aba18d-04c5-4c7e-b522-557569478e88.png)

### What is happening
404 page displays

### What should happen
Either timer should be non functional or "You have been signed out" page should display

**Comment by jonhurrell** [comment]
We've agreed to stop the modal count a 1 second and stop the forwarding to another page.
