### ISSUE TITLE
In-page navigation

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#327]
What
Improve navigation within a pattern or component when we add more and more content to the page.

Why
To give users easier access to parts of the page they require, have better and clearer placement of information, add more information as/when required without adding more weight to the page (within reason).

## Done when

- [x] Team has run through mural / provided feedback
- [x] Shared with wider designer team for feedback
- [x] Templates / more understanding of what needs/could to be on each page
- [x] Prototype and test?

## Who needs to know about this
Wider design team
Design system team
Accessibility team?

Related stories

Anything else

**Comment by michaelcattell** [comment]
Mural link with potential designs and Martin's feedback:
https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1639572715129/5b1cdc137dde9d822d6a3b9e40f1143798dc26f4?sender=u55e00bdc184c14d847fb8934

**Comment by mitz-lad** [comment]
Reviewed initial ideation of multiple page and single page solutions within team. Next step: Further refinement required to share with wider design team and incorporate work done on [standard content format #258 ](https://github.com/dwp/design-system/issues/258).

**Comment by mitz-lad** [comment]
Moving forward with [single page solution](https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1639572715129/5b1cdc137dde9d822d6a3b9e40f1143798dc26f4?wid=0-1655310005476) in the first instance, mocking up page content. 

@simoneduca @dtaylorbrown Styling work will be required for left hand navigation to follow the same look and behaviour of the  [Accessibility manual](https://accessibility-manual.dwp.gov.uk/tools-and-resources/basic-accessibility-checks) or [GDS design system](https://design-system.service.gov.uk/styles/typography/)
