### ISSUE TITLE
Snags after new nav release

### ISSUE THREAD

**Issue by simoneduca** [dwp/design-system#348]
- [x] remove latest updates box
- [x] remove banner
- [x] 301 redirect
- [x] subnav weird spaces

## Content fixes (@martinwake)
- [x] Remove key-details from design examples
- [x] Remove post-code lookup from design examples
- [x] Remove hint-text from to-do
- [x] Remove add another thing from in progress
- [x] /contribute missed spacing 'To help develop a proposed pattern'

**Comment by dtaylorbrown** [comment]
https://gitlab.com/dwp/dwp-design-system/main-site/-/merge_requests/171

**Comment by martinwake** [comment]
https://gitlab.com/dwp/dwp-design-system/main-site/-/merge_requests/172
