### ISSUE TITLE
Guidance on add another prototype how to integrate code

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#357]
## What

Add another patter documentation which details how other designers and developers can integrate this pattern into their prototypes, this is related to  #367 

## Why

It's quite a complicated pattern especially in the way that we deal with the data, giving some documentation with code samples and explanation should help reduce this complexity.

## Done when

- [x] Documentation is provided
- [x] Documentation can be viewed in a public location

## Outcomes

Informative documentation on how best to integrate the add another pattern

**Comment by dtaylorbrown** [comment]
Docs can be found within the internal pizza prototype repo 🙂

**Comment by dtaylorbrown** [comment]
Public documentation here: https://design-system.dwp.gov.uk/patterns/add-another-thing/example
