### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#370]
Add a site map to the design system main site.

~This should use the appropriate XML format https://www.sitemaps.org/~ 

- [x] Investigate if we need a sitemap

We investigated this and found two different reasons for using a sitemap. One is for SEO, which is what the XML format applies to and is probably unnecessary. The other is for accessibility, where an HTML sitemap is a WAI technique for meeting the criterion 2.4.5 "Multiple Ways", giving users several options for how to navigate to an item: https://www.w3.org/WAI/WCAG21/Techniques/general/G63.

In our case we're doing it for accessibility so we'll go ahead with an HTML sitemap page.

**Comment by mitz-lad** [comment]
@simoneduca  Quick mockup of the sitemap page.

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/72147702/176884193-0fa38b73-4ceb-46bd-8974-de56c578da10.png">
