### ISSUE TITLE
Investigate how to use a different favicon within the prototype kit

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#378]
## What
If setting up the prototype kit for an internal service we need a way to override the default crown favicon and replace with our DWP favicon.
The prototype kit inherits the favicons from `template.njk` within the `headIcons` block. 

## Why
The crown is part of the GOV.UK brand, so we should be using and help others to use a DWP one.

## Done when

- [ ] We can use a different favicon without any being overwritten by the default govuk one upstream.

**Comment by dtaylorbrown** [comment]
@jonhurrell had a quick look around, looks like the prototype kit `layout.njk` extends the govuk frontend `template.njk` [here](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/template.njk) so looks like we would need to provide our own template which would replace this to over-write the favicon.

Also if we used an SVG we could change the background if a user has a preference for dark mode

**Comment by dtaylorbrown** [comment]
Closing as discussed we would need to maintain our own version of `template.njk` which **could** be a maintenance nightmare
