### ISSUE TITLE
Internal footer a11y team audit

### ISSUE THREAD

**Issue by simoneduca** [dwp/design-system#381]
- axe: *1 minor issue*
- wave: *no issues* found
- browserstack - tested chrome, safari, ff and edge on windows, big sur, ios and android. *No issues* found.
- voiceover: no issues found using mac OS VoiceOver

Guides to help complete the templates

- https://support.apple.com/en-gb/HT210539 VoiceControl
- https://support.apple.com/en-gb/guide/mac-help/mh35715/mac Zoom
- https://support.apple.com/en-gb/HT210978 Zoom 
- https://support.apple.com/en-gb/guide/voiceover/toc VoiceOver

Complete a11y team templates:

- [x] Automated test template
- [x] VoiceOver test template
- [x] AppleZoom test template 
- [x] VoiceControl test template
- [x] @jonhurrell to email Nicki the evidence

**Comment by jonhurrell** [comment]
Move this back to cover off the a11y team's testing templates.

**Comment by dtaylorbrown** [comment]
moved to ready to review, since all tasks are complete with the exception of emailing evidence
