### ISSUE TITLE
Accessibility testing - hint text

### ISSUE THREAD

**Issue by dtaylorbrown** [dwp/design-system#386]
- [ ] axe
 - [ ] wave
 - [ ] browserstack - test chrome, safari, ff and edge on windows, big sur, ios and android
 - [ ] voiceover

Complete a11y team templates:

 - [ ] Automated test template
 - [ ] VoiceOver test template
 - [ ] AppleZoom test template
 - [ ] VoiceControl test template

Guides to help complete the templates

https://support.apple.com/en-gb/HT210539 VoiceControl
https://support.apple.com/en-gb/HT210978 Zoom
https://support.apple.com/en-gb/guide/voiceover/toc VoiceOver

**Comment by simoneduca** [comment]
"Not applicable" as we don't provide any actual code examples to test.

**Comment by dtaylorbrown** [comment]
closing, see above comment
