### ISSUE TITLE
Update Prototype kit guidance for using the footer component

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#394]
## What
Update guidance to include how to include our footer within the prototype kit.

## Done when

- [x] Update [discussion](https://github.com/dwp/design-system/discussions/347)

**Comment by jonhurrell** [comment]
@simoneduca @dtaylorbrown Please can you review the guidance.

**Comment by simoneduca** [comment]
@jonhurrell LGTM 👍
