### ISSUE TITLE
Update DS website left hand navigation

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#399]
## What
Update left hand navigation to include two additional nonfunctional sections: Pages and Retired patterns.

![image](https://user-images.githubusercontent.com/26182217/173554048-59077406-05ba-4bfb-a980-85b876e2a2c3.png)

## Why
Pages like the Cookies page and Internal services page are different from other patterns that meet a specific user need. They're sample pages aimed at saving designers work and we're likely to need more of these in future.

The Retired patterns separator makes it clearer that these patterns are retired and separate from others. It will also mean removing the Retired patterns landing page at https://design-system.dwp.gov.uk/patterns/retired-patterns

## Done when

- [x] New nav published
- [x] retired-patterns page removed
- [x] redirects set up for retired-patterns URL and Cookies page URL (and any other moved pages)

**Comment by jonhurrell** [comment]
Pushed changes. @simoneduca To merge cookies-page branch and check everything aligns/works.

**Comment by martinwake** [comment]
If the [Internal service page](#457 ) is published before the Cookies page, this change should be made at that point (Internal services page also belongs in the Pages section).

**Comment by jonhurrell** [comment]
@simoneduca I’ve got this work ready for the page to be added (the urls will need to be checked) in the new-navigation-item branch. It was just merged with main.
