### ISSUE TITLE
Fix dwp-frontend documentation

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#400]
## Related documentation

https://gitlab.com/dwp/dwp-design-system/frontend

## Suggestion

Needs to be rewritten now that dwp-frontend is available on npm

## Evidence (where applicable)

Documentation begins "Since dwp-frontend is not currently available on public npm...."

**Comment by jonhurrell** [comment]
Fixed https://github.com/dwp/design-system/issues/548
