### ISSUE TITLE
Update side navigation styling

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#403]
## What
Update the side navigation styling for the design system to look and behave the same as [Accessibility manual](https://accessibility-manual.dwp.gov.uk/tools-and-resources/basic-accessibility-checks) or [GDS design system](https://design-system.service.gov.uk/styles/typography/).

![side-navigation](https://user-images.githubusercontent.com/72147702/179478776-eb2c79fe-c6bc-4b54-8d14-12a0ff45536e.png)

## Why
The current side navigation styling is not consistent with other examples in Gov. And the introduction of subsections within pages requires a more prominent visual indicator of the navigation hierarchy.

## Done when
- [ ] Styling of side navigation is updated to match the attached mock up

## Outcomes
The navigation will be more consistent with other Gov side navigation.

**Comment by mitz-lad** [comment]
@simoneduca I found a couple of niggles (see below) but other than that it's looking good to me...

**Not all side navs using the new styles**
The new styles don't seem to be applied to the Get started and meta pages I'm basing this off that they don't have the left border when selected

<img width="120" alt="image" src="https://user-images.githubusercontent.com/72147702/187403728-a7a5880e-8c89-4ffc-94de-b4b1847f217b.png">


**Active left border is further from the label for links without a subsection** 

<img width="120" alt="image" src="https://user-images.githubusercontent.com/72147702/187404107-eb025c6c-a49b-4126-bc03-cfc0dc911443.png">

<img width="120" alt="image" src="https://user-images.githubusercontent.com/72147702/187404166-b1c3c110-6cb2-4933-82e1-196cd2a8c87a.png">


I found turning off the following css is more like the intended design in terms of the proximity - not sure what else this would effect by removing it

`.app-subnav__section-item--current {
  margin-left: -14px;
  padding-left: 14px;
}`

**Comment by simoneduca** [comment]
good catch. Having a look now.

**Comment by simoneduca** [comment]
Should be fixed now https://sidenav-styles.design-system.dwp.gov.uk/get-started
