### ISSUE TITLE
Contact preferences

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#426]
## What
Users of DWP services will often need contacting, to notify them of a decision or to update them on progress.

## Why
How and when we do this should be consistent.

## Anything else

- when and how to contact users
- how to ask users for their preferred contact methods
- how to help users keep their contact details up-to-date
- not everyone has an email address or a mobile phone. 
Some people can read SMS messages but not take voice calls. Give people choices about how you will contact them. Let your users tell you how, when or why they would like to be contacted by you.
- Let people change their contact preferences
People’s situation and therefore preferences change over time. Let your users change their contact preferences with you.

#### Services

- Apply for a National Insurance number
- Register to vote
- Universal credit
- Carer's Allowance

**Original issue information:** 25 July 2019 @jon-houghton https://github.com/dwp/design-system-community-backlog/issues/7

### User Flow
[Contact.preferences.pdf](https://github.com/dwp/design-system/files/5219495/Contact.preferences.pdf)

**Comment by jonhurrell** [comment]
Closing as this has moved into the [roadmap](https://github.com/dwp/design-system/issues/244) to deliver.
