### ISSUE TITLE
Agent confirm actions

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#430]
## What
Confirm an action on agent screen.

## Why
There are examples of confirming to users that an action is complete through banners, different to the standard confirmation pages.  These seem to be in admin systems (both internal and external) and put the confirmation in a banner at the top of another page.

#### Research

We researched this approach somewhat on Prepare for UC which is where the previous example is from.

Users often missed the bar itself, most assume the thing they were doing had been saved but were often left confused and were unsure of next steps.

The solution hadn't taken accessibility in to account, we research with various users with access needs using a variety of assistive tech. Screen reader users in particular struggled. We recommended updating to act in much the same way as the error summary which helped somewhat.

In comparison we're currently researching another service for internal user for Move to UC. We stuck with the standard confirmation page and users have been very positive about the conf page, as they'd expected it would dump them back where they started as other services they've used do this sometimes, but liked the reassurance that the task had completed/saved.

#### Services

- Prepare for UC

**Original issue information:** 14 May 2018  Chris Armstrong https://github.com/dwp/design-system-community-backlog/issues/35

**Comment by jonhurrell** [comment]
Duplicate of https://github.com/dwp/design-system/issues/431
