### ISSUE TITLE
Add MVP Google analytics to the design systems site

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#46]
### What work do we need to do?
- [x] Add a cookie consent banner
- [x] Arrange a performance workshop with Catherine Hopes team to discuss the performance measures
- [x] Include GA code in scripts
- [x] Setup staging area environment for performance team to implement and test GTM effectively
### Why are we doing it?
To help us better support the design-system going forward and to start the basis of figuring out what success looks like.

**Comment by jonhurrell** [comment]
Updated to include new work from the email (forwarded on).

**Comment by simoneduca** [comment]
https://developers.google.com/tag-manager/devguide#restricting-tag-deployment
