### ISSUE TITLE
Key Details font scale

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#466]
## Describe the issue
Documented by @htmlandbacon on [GitLab](https://gitlab.com/dwp/dwp-design-system/frontend/-/issues/13)

**Comment by jonhurrell** [comment]
Done when:
- [ ] https://accessibility-manual.dwp.gov.uk/tools-and-resources/basic-accessibility-checks/2-responsive-design-how-to-test
- [ ] Browser matrix results
- [ ] Test front-end release candidate

**Comment by HelenOsg** [comment]
Browser matrix testing page https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133031362646/Testing
