### ISSUE TITLE
Find an address: Working example

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#485]
## What
Create a working example of the find address pattern on the order pizza service, using the following journey and an address lookup API.

Example screen designs on [Mural: Find an address](https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1657636707008/e8e422d466ec6f13e6b101899d14a9cf630b0500?wid=0-1661939731655). 

![find-address-journey-complete](https://user-images.githubusercontent.com/72147702/193556461-9cd04b0c-1baf-4b77-84a8-7ee004abeeac.png)

## Why
So designers can see a practical example of the find an address principles put into practice.

## Done when

- [ ] Setup journey and routes
- [ ] Add relevant components to each page
- [ ] Content implemented
- [ ] Accessibility testing

## Outcomes
A working version of the find an address pattern that can be linked from the DS for users to view and try out. 

## Who needs to know about this
- DS team

## Related stories
https://github.com/dwp/design-system/issues/458 

## Anything else
We don't have specific screen designs and content for the pizza service so some design will need to be done to determine this for the content. There are some mockups we did initially (see attached), which would need adapting. These are also available on the Mural via the link above. 

[Find an address - Designs.pdf](https://github.com/dwp/design-system/files/9725817/Find.an.address.-.Designs.pdf)

**Comment by mitz-lad** [comment]
Put an updated journey and initial screens together for takeaway prototype to include the find an address pattern. Updated the order and steps for the journey as well as some of the components on the screens. 

@HelenOsg @martinwake @simoneduca can I get your input on the updated journey, screens and content please? Mural board: https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1666687110513/21faf0fd7b2203c6dc71e99efb22f3eb75ae8a09?sender=ub2947a7492ef409e91952034

![DWP Design System Order takeaway - Order takeaway - journey and screens v1_2022-10-26_15-10-17](https://user-images.githubusercontent.com/72147702/198068592-ddd6ec19-b013-42ca-bbac-1bd666df3e57.png)

**Comment by mitz-lad** [comment]
@simoneduca did a bit of testing and found the following bugs

### 1. No address found: conditional text formatting
**Expected**
If the user only enters in a postcode and it is not found then the error message should read 'We could not find an address that matches **se17 2nl.** You can search again or enter the address manually.'

**Actual**
Message currently reads incorrectly with the additional  `and .` 'We could not find an address that matches **se17 2nl** and . You can search again or enter the address manually.'

<img width="350" alt="Screen Shot 2023-03-21 at 08 39 10" src="https://user-images.githubusercontent.com/72147702/226561667-25f23e71-97ea-4b3a-b359-9f228b2824cf.png">

---

### 2. No address found: going to wrong template
**Expected**
When the address is not found the user should be directed to the no address template.

<img width="400" alt="Screen Shot 2023-03-21 at 08 41 07" src="https://user-images.githubusercontent.com/72147702/226563252-31eed7e1-93ee-4f2b-bd57-721d0953292b.png">


**Actual**
This particular search went to the result screen. Not sure what conditions determines which route it's going to. _NB: that particular search is a correct address and should return a result so not sure if that has anything to do with it._

<img width="400" alt="Screen Shot 2023-03-21 at 08 41 07" src="https://user-images.githubusercontent.com/72147702/226562329-360c5974-9b70-4ccf-94cb-587568bd6640.png">

---

### 3. First line or building number not always appearing
**Expected**
First line of address or building number is displayed as part of address.

<img width="400" alt="Screen Shot 2023-03-21 at 08 41 07" src="https://user-images.githubusercontent.com/72147702/226565758-f033ba36-f18d-48bb-a90d-2bd5af4b6164.png">

**Actual**
Flat numbers are missing on this particular search.

<img width="400" alt="Screen Shot 2023-03-21 at 08 41 07" src="https://user-images.githubusercontent.com/72147702/226565892-9c3ba534-d694-44f5-bef7-a35f432133ef.png">

---

### 4. Manual address is pre-populating data
**Expected**
When going on manual address the form should always be cleared, so any potentially erroneous data is not persisted.

**Actual**
Address field is being pre-populated by search data.

<img width="400" alt="Screen Shot 2023-03-21 at 08 41 07" src="https://user-images.githubusercontent.com/72147702/226569313-fd975762-3187-4afe-8af2-fca28b1a79fa.png">

---

**Comment by jonhurrell** [comment]
Outstanding items from the sprint review @martinwake @simoneduca :

- [x] Reflow the user journey to begin with asking address
- [x] Add hint text to the ask address screen
- [x] Enter manual address to look the same as https://design-system.service.gov.uk/patterns/addresses/

Journey to start with:
<img width="784" alt="Screenshot 2023-03-22 at 10 33 24" src="https://user-images.githubusercontent.com/809482/226876961-2ff8cc4b-797e-46bf-b8c1-05500f8f0e7a.png">

Address journey first:
<img width="784" alt="Screenshot 2023-03-22 at 10 35 29" src="https://user-images.githubusercontent.com/809482/226877353-b8713f1b-877b-41bc-ab27-864e0e66e2c0.png">

Route to different add another examples:
<img width="784" alt="Screenshot 2023-03-22 at 10 37 29" src="https://user-images.githubusercontent.com/809482/226877720-b67ab419-5e48-4fde-8886-1c8800f707c2.png">

**Comment by mitz-lad** [comment]
The confirm address page when coming from the manual entry screen is different from when you come from search results... the intended design is on Mural: https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1666687110513/21faf0fd7b2203c6dc71e99efb22f3eb75ae8a09?wid=0-1666776557679

- [x] Remove 'Search again’ link (we haven't come from a search so we don't this)
- [x] Remove ‘Use a different address’ (we haven't selected an address or have a results screen in this journey)
- [x] Add ‘Find address’ link which goes to the 'Where should we deliver your order?' step

@simoneduca

**Comment by martinwake** [comment]
When there are multiple results the "use a different address" link should return users to the list of search results: currently it looks empty:

![image](https://user-images.githubusercontent.com/26182217/227961050-f8f3423f-6c25-4cbe-8b50-ef3a074f7d59.png)

**Comment by martinwake** [comment]
When there is only one address the intro should read "1 address found" not "1 addresses found"

**Comment by martinwake** [comment]
- [x] Confirm screen for postcode only search, single result: remove "Use a different address" link (test search: SW1A 1AA)
![image](https://user-images.githubusercontent.com/26182217/228200794-c786edfe-eceb-44d6-8484-fed2206938fd.png)

- [x] Confirm screen for postcode + building name search, single result: remove "Use a different address" link (test search: S11 9DG, 21)
![image](https://user-images.githubusercontent.com/26182217/228201534-e94cc186-b608-49e9-becd-db7816d29863.png)

- [x] When there are no results the content should be as follows:
![image](https://user-images.githubusercontent.com/26182217/228195329-dd0e93ad-657d-40e2-9762-289766c49bbe.png)

- [x] Pizza option complete screen:
  - [x] should have "start again" button which clears data and goes back to start page, instead of "Order more fake pizza" link, same as Chinese option
  - [x] should play back address as per Chinese option ("we'll deliver your order to [address]") (screenshot shows current screen)
![image](https://user-images.githubusercontent.com/26182217/228196459-c03c1067-f0d5-42e6-81a3-8702ffacdc49.png)
