### ISSUE TITLE
Make homepage tiles clickable

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#488]
## What
In the tiles on the design system homepage that link to individual patterns or components, make the headings clickable. Possibly also remove the second link and make the whole tile area clickable.

## Why
Makes the content shorter; matches a common expectation of how tiles and headings work.

## Done when

- [x] Decide whether or not to implement this

## Who needs to know about this
Design System Team

**Comment by jonhurrell** [comment]
I recall a11y issues with this approach.
