### ISSUE TITLE
Integrate UC design patterns

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#49]
### What work do we need to do?
Establish how best to include the UC specific design patterns.
### Why are we doing it?
The user need is to have a single place to share and discuss the components and patterns. There's a catalogue of UC patterns, discussion and evidence that would benefit from being more inclusive in its sharing.
### Related stories

- [ ] Feature: Create prototype showing UC specific patterns sitting alongside others
- [ ] Chore: Can we get VPN and Confluence access to see the existing audit @simoneduca 
- [ ] Chore: @simoneduca arrange a meeting with Kamil and Kirsty to discuss their prototyping kit, how it works, updated, integration with git for PRs, is it still needed
- [ ] Chore: @Ash-Wilson to invite @jonhurrell to Wednesday UC Designers meet
- [ ] Docs: Process alignment to standardise what a pattern is and documented

**Comment by jonhurrell** [comment]
@michaelcattell to update ticket content.

**Comment by michaelcattell** [comment]
Discussed with Jon and will contact UC to attend their show and tells and see the latest with their design system

**Comment by michaelcattell** [comment]
Closing due to attending monthly (U.C led) updates on design library.

Will make new tickets if required to add any work to our backlog.
