### ISSUE TITLE
Working group feedback

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#499]
- [x] Add examples of results page and error page
- [x] Clarify position on pagination and long lists of results

**Comment by mitz-lad** [comment]
Updated the preview site with examples of the results and error page. Also updated the journey image to include the error page. https://find-an-address.design-system.dwp.gov.uk/patterns/find-an-address

**Comment by mitz-lad** [comment]
Images and content updates done. 

Closing this ticket as we feel we're in a good place to send out the link to the preview and collate feedback from the wider community.
