### ISSUE TITLE
Feedback from UCD community

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#500]
Circulate preview of pattern to wider UCD community before publishing on live site.

- [x] Announce on email and Slack channels
- [x] Publicise at show and tells

**Comment by mitz-lad** [comment]
We have a slot at the next Interaction, Service Design and Front End Community call on 27/10/2022 between 14:00-15:00. 

We have 10-15 minutes, which we can use to focus on Find an address, just need to save a bit of time to give update on navigation workshop.

**Comment by martinwake** [comment]
We also have up to 30 minutes on the Content Design show and tell on 27 October.
