### ISSUE TITLE
Hide action scripting on cookie banner

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#51]
**Describe the bug**
Once you've taken an action to accept or reject a cookie, the banner updates with a link to hide the banner. Clicking hide should dismiss the banner, but it currently doesn't do anything.

**To Reproduce**
Go to cookie page https://cookies-management.design-system.dwp.gov.uk/index, press either button to accept or reject so update the banner, to reveal the Hide action.

**Expected behaviour**
Clicking hide will remove the banner.

**Additional context**
The 'hide' is currently using the link element, as it doesn't change the url, use a button element to trigger the scripting. https://www.a11yproject.com/posts/2019-02-15-creating-valid-and-accessible-links/

[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by simoneduca** [comment]
Although this works locally, it doesn't on the test address https://cookies-management.design-system.dwp.gov.uk/index
I don't have access to the AWS env (I will ask to get it), so for now I'll inject a script in the body of the element to trigger the hiding action.

**Comment by simoneduca** [comment]
@jonhurrell Script is now deployed to https://cookies-management.design-system.dwp.gov.uk/, so cookies are managed with no page refresh. Next I'll look into a solution for when js is disabled and at the cookie-policy journey.

**Comment by simoneduca** [comment]
Fixed the policy journey and added a switch for a `noscript` scenario. Works well in dev but the deployed version still shows the problem with confirmation banners 🙄
