### ISSUE TITLE
Document adoption of components and patterns 

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#512]
## What

Document the services that are using components and patterns from the DWP Design System

## Why

Track and document adoption across services so we can gain insight and research on their use. This will mean we can identify areas of improvement or where services have deviated from the design, it will also allow us to document when designs have been tested and ratified by services.

## Done when

- [x] Identify service teams that are using components and patterns
- [x] Document in confluence pages
- [ ] Outreach to service teams for insight and research
- [ ] Where possible get screenshots of use
- [ ] Update Design System site with information
- [ ] Use insight to plan iterations to designs

## Outcomes

Robust and researched designs for components and patterns in the DWP Design System

## Who needs to know about this

UCD community
Product managers

**Comment by HelenOsg** [comment]
Mural board set up to capture services using patterns - https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1670440791694/fac4cb7b6a1733f843f3c4d05dc303edca13379e?sender=ub9ed1118cc28cdee9b850540

**Comment by jonhurrell** [comment]
Documented use of components on Confluence. The Heroku plan change and migration means we don't have a source of truth for the prototypes any more. This needs to be a rolling task every 6-12months going forward.
