### ISSUE TITLE
Definition of good enough

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#514]
## What
A definition of good enough that will help to decide whether patterns or components can move through to the next step and ultimately be published.

## Why
Having an idea of what 'good enough' looks like will help us to critique the proposed work and decide if it should be published.
It will give us confidence in the work and our decision making process.

## Done when

- [ ] Workshop with Design System team on what 'good enough' could look like

## Outcomes
A clearer understanding of what work that is ready to move on and be published looks like.

**Comment by jonhurrell** [comment]
Folded into milestone definitions on new roadmap template.
