### ISSUE TITLE
Timeout modal overlaps mobile viewport

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#525]
## Describe the issue
When viewing the example session timeout modal in the "Manage a session timeout" pattern, the modal is slightly too wide for a mobile viewport.

## Steps to reproduce the issue
Visit https://design-system.dwp.gov.uk/patterns/manage-a-session-timeout/examples/signedin on a mobile or with a mobile emulator.

## Actual vs expected behaviour
The content and window should reflow to match the viewport size.

## Environment (where applicable)
Checked on Safari on an iPhone SE running iOS 16.2
![image](https://user-images.githubusercontent.com/26182217/212700757-9d2a937c-79a9-4fba-bb39-4f345ab3f54d.png)

**Comment by simoneduca** [comment]
preview of the fix https://session-bug.design-system.dwp.gov.uk/patterns/manage-a-session-timeout
