### ISSUE TITLE
Navigation: Internal services header navigation - draft guidance

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#531]
Create draft guidance for the internal services header navigation component.
Using the updated template for guidance pages in the confluence page but amending as much as required - this template has not been used for a component before.

https://github.com/dwp/design-system/issues/496

## Done when:

- [x] Draft content written
- [ ] Examples built and included
- [ ] Content agreed

**Comment by HelenOsg** [comment]
Draft guidance currently placed in confluence - https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/132971102443/Draft+content+-+Navigation

Agreed that this will replace the internal service header page as the navigation will be placed within the header component.

**Comment by HelenOsg** [comment]
https://header-nav.design-system.dwp.gov.uk/components/internal-service-header

**Comment by HelenOsg** [comment]
variant - https://primary-nav.design-system.dwp.gov.uk/components/primary-nav

**Comment by HelenOsg** [comment]
Agreed that would progress with having the nav component guidance in a separate page to the internal header guidance. 
Example will be included as a variant of the header in the internal service header page guidance page.
Internal service page template to be updated with the header nav component
Decision to be made on the title of the component (main navigation, header with navigation, internal header with navigation, navigation)
Include guidance on mobile viewports

**Comment by HelenOsg** [comment]
Updated https://primary-nav.design-system.dwp.gov.uk/components/primary-nav 
Changed title to header with main navigation
Added winter fuel payment and get your state pension to research area
Examples need updating to reflect the component.
Examples needed:
Header with main navigation
Header with main navigation and more drop down
Mobile view

**Comment by martinwake** [comment]
Draft content on preview branch
