### ISSUE TITLE
Update contribution guidance

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#532]
## Related documentation
It's no longer clear how to raise a new issue in the community backlog or report a bug on an existing pattern.

## Done when

- [x] https://design-system.dwp.gov.uk/community/contribute is rewritten with updated guidance
- [x] All references to previous backlog at https://github.com/dwp/design-system-community-backlog/issues are updated 
- [x] GitHub issue template is updated

## Suggestions

Review and refresh our GitHub issue templates if we don't want people to use these any more (other than internally): 
![image](https://github.com/dwp/design-system/assets/26182217/8e2366cd-19b4-457b-a58d-aa796cd72b50)

Add a "report a problem" link to the pattern and component templates.

Review and update the "Backlog" page on the website - could this be a link to the backlog on GitHub instead?

Could we copy the GOV.UK method of automating a fork and pull request? Or is this difficult given that we use GitLab? https://design-system.service.gov.uk/community/propose-a-content-change-using-github/

**Comment by jonhurrell** [comment]
@jonhurrell to review branch.

**Comment by jonhurrell** [comment]
@martinwake I think that's a good primer. I'll move over to done. We can pickup the GitHub templates at a later time.
