### ISSUE TITLE
Add test to nunjucks components

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#54]
**Is your feature request related to a problem? Please describe.**
We need a level of assurance that once the the cookie banner component is included in a build, the HTML output matches our spec for it.

  **Describe the solution you'd like**
A test included in the component files that checks output against an expected snapshot.

  **Additional context**
[See how GDS uses approaches this](https://frontend.design-system.service.gov.uk/testing-your-html/#test-if-your-html-matches-gov-uk-frontend) (hat tip @htmlandbacon) [govuk-elements-nunjucks](https://github.com/htmlandbacon/govuk-elements-nunjucks)
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by simoneduca** [comment]
I've set up dwp-frontend https://gitlab.nonprod.dwpcloud.uk/design-system/frontend and will push the cookies stuff today, hopefully with tests.

**Comment by simoneduca** [comment]
Follow this example https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/cookie-banner/template.test.js
