### ISSUE TITLE
Timeline component: reported bug

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#540]
## Describe the issue
Email received highlighting issue with Timeline component.
 
**From:** andy.porter@landregistry.gov.uk
**To:**  dwp-design-system@engineering.digital.dwp.gov.uk
**Cc:** rosie.brave@landregistry.gov.uk

> Hi,
> 
> Borrowing your [timeline component](https://design-system.dwp.gov.uk/components/timeline) to try it out on a caseworking system here at HM Land Registry
> 
> I couldn’t get it working for a bit – then I realised the class names in the HTML and CSS don’t match.
>
> You’re missing ‘__events’  from the class names in the CSS.
>
> 
> Regards
> 
> Andy

**Comment by simoneduca** [comment]
The "_events" suffix is not missing on the dwp-frontend css for the timeline component. I'll email Andy asking clarifications. Closing for now.

**Comment by simoneduca** [comment]
The mismatch was in the main-site HTML/CSS samples. Fixed now.
