### ISSUE TITLE
Components/layout at 100% width for agents

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#541]
## Context
We've seen a few services start to use 100% width - we need a consistent view on how components should behave when scaled to this view.

We might also want to consider layout guidance (this had an ad-hock 2/40%/40% grid) as I've already seen some variations between prototypes and production code.

## Additional information
The current versions I've seen have largely ended up fine at 1900px but then misalign due to a mix of percentages and fixed with padding used on the components. 

Be good to add some visuals/thoughts @colpas @petejobesdigitaldwp

**Comment by colinpassant1** [comment]
![Splitscreen](https://github.com/dwp/design-system/assets/62711290/85c5e52f-147f-4c63-a1f7-5f8341480e3b)

Here is an example of where the screen needs to be 100% width. In this scenario our users needs to see information side by side, to enable them to read and cross reference whilst capturing information.

**Comment by htmlandbacon** [comment]
Chatted to @jamesashcroft about this and suggestion is we revisit this as a thing when we know more about the use cases so closing for now.
