### ISSUE TITLE
Housekeeping: Team page updates and DWP Logo 

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#542]
## What
Housekeeping tasks

- Team page update
- Add DWP logo to header 

## Team page done when

- [x] Removed Helen's details
- [x] Removed any unused images
- [x] Remove '(interim)'from Mitz's title
- [x] Add Colin to team page
- [x] Add Claire to team page

## DWP logo done when

- [x] Added logo to header
- [ ] Cross browser tested
- [ ] Accessibility tested

## Related issues

- [Favicon not visible using Dark browser themes #489](#489)

**Comment by mitz-lad** [comment]
Updates on [feature/house-keeping](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/feature/house-keeping?ref_type=heads) branch. This branch also contains update to favicon see [Favicon not visible using Dark browser themes #489](#489)

Requires cross browser testing and accessibility testing on logo to release.

**Comment by mitz-lad** [comment]
### Team page updates
Created new branch [f-team-page](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/f-team-page?ref_type=heads) with fixes as [feature/housekeeping](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/feature/house-keeping?ref_type=heads) branch got messy with other fixes.

Preview: https://f-team-page.design-system.dwp.gov.uk/index

**Added default avatar for team page profile images**
<img width="300" alt="image" src="https://github.com/dwp/design-system/assets/72147702/8e92f1f6-b6b3-4609-a1f3-9e4f193edee8">


**Fixed line break issue** 
Currently email addresses break the layout
<img src="https://github.com/dwp/design-system/assets/72147702/7bc0853c-edc2-4109-8e81-4a836ebe3f60" width="300">

Fixed by changing html from `<ul>` to `<dl>` as content is key-value pairs and setting line break behaviour.
<img src="https://github.com/dwp/design-system/assets/72147702/bc3fa604-2e1c-4b70-99f6-a61d6b161546" width="300">

**Comment by mitz-lad** [comment]
### Added DWP logo to header
Created new branch [f-logo](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/f-logo?ref_type=heads) with changes as [feature/housekeeping](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/feature/house-keeping?ref_type=heads) branch got messy with other fixes.

Preview: https://f-logo.design-system.dwp.gov.uk/index


<img width="1154" alt="image" src="https://github.com/dwp/design-system/assets/72147702/31cef998-1714-44ad-b4f1-af241eceb706">

<img width="657" alt="image" src="https://github.com/dwp/design-system/assets/72147702/50ee0147-7c9c-409a-a8c7-34c4cf91a269">

<img width="515" alt="image" src="https://github.com/dwp/design-system/assets/72147702/362e5d34-1eee-469a-914b-ffd82dcffb20">

<img width="322" alt="image" src="https://github.com/dwp/design-system/assets/72147702/52cfe302-1ce2-43d4-900c-1c0696c3a501">
<br><br>

- Added SVG logo to header
- CSS for responsive behaviour (Tested in Chrome)
- Checked for relative url for different pages - needs seconds eyes just in case I missed anything

SVG is about 46kb, and has been implemented as an image, so it should be cached after the the initial load.  Optimisation tool reported by gzipping the file it can be reduced to about 17kb. Adding an additional task to the ticket for this.

Header has been implemented in Chrome Version 120.0.6 - accessibility and browser testing will be required.

**Comment by jonhurrell** [comment]
> ### Added DWP logo to header
> Created new branch [f-logo](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/f-logo?ref_type=heads) with changes as [feature/housekeeping](https://gitlab.com/dwp/dwp-design-system/main-site/-/tree/feature/house-keeping?ref_type=heads) branch got messy with other fixes.
> 
> Preview: https://f-logo.design-system.dwp.gov.uk/index
> 
> <img alt="image" width="1154" src="https://private-user-images.githubusercontent.com/72147702/296706103-31cef998-1714-44ad-b4f1-af241eceb706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTU1MzQsIm5iZiI6MTcwNTkxNTIzNCwicGF0aCI6Ii83MjE0NzcwMi8yOTY3MDYxMDMtMzFjZWY5OTgtMTcxNC00NGFkLWI0ZjEtYWYyNDFlY2ViNzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZDcxNjE0MjVkNWM0NDJlZWY0ZWEwYTc0NmE0ZmZlYWZiYTJkNzlkODgzNTVkNDI1OWVlNGQzNmMzMzcwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V9gxeTHgZDefSMg0akW2Dqr9aLVbVixRlbNSOjBL8DA"> <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/72147702/296706343-50ee0147-7c9c-409a-a8c7-34c4cf91a269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTU1MzQsIm5iZiI6MTcwNTkxNTIzNCwicGF0aCI6Ii83MjE0NzcwMi8yOTY3MDYzNDMtNTBlZTAxNDctN2M5Yy00MDlhLWE4YzctMzRjNGNmOTFhMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MDFlZTVhZTExOGE2ZjNkNTA0N2YzMzQ3NjM1MzlkOWUzMzgwMzlmODM4NTA1MDM2OTQzMGJjZDkzMjU0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cX1dzTNlF-zbDKvgjuiDSfflX2XvAFeLY5dRw3h4Iyg"> <img alt="image" width="515" src="https://private-user-images.githubusercontent.com/72147702/296706545-362e5d34-1eee-469a-914b-ffd82dcffb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTU1MzQsIm5iZiI6MTcwNTkxNTIzNCwicGF0aCI6Ii83MjE0NzcwMi8yOTY3MDY1NDUtMzYyZTVkMzQtMWVlZS00NjlhLTkxNGItZmZkODJkY2ZmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMzkzYjdmZDdiZTFmMGI1MzMyYTczNTk2YzA1Njg3MTBlMzk3ODRjYWEyNTFiZWY0Y2I2OTMwZGMyNzJhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BNugWXEnOqELl44yieSrnvUTuoa5HbzOg7Dcez_-j0"> <img alt="image" width="322" src="https://private-user-images.githubusercontent.com/72147702/296706949-52cfe302-1ce2-43d4-900c-1c0696c3a501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTU1MzQsIm5iZiI6MTcwNTkxNTIzNCwicGF0aCI6Ii83MjE0NzcwMi8yOTY3MDY5NDktNTJjZmUzMDItMWNlMi00M2Q0LTkwMGMtMWMwNjk2YzNhNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZjk4MjkxMjRjNDA5YjBlMDM4N2M1YjdhYzE4OTYzOTZlMzY3MDRkYjU0MmRmOTliZTczYTg4NjE0OGRlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aR4S3qG4aNdqaLqnMXFU1hy5nWpTWC0TDMjEwSgH4os">
> 
> * Added SVG logo to header
> * CSS for responsive behaviour (Tested in Chrome)
> * Checked for relative url for different pages - needs seconds eyes just in case I missed anything
> 
> SVG is about 46kb, and has been implemented as an image, so it should be cached after the the initial load. Optimisation tool reported by gzipping the file it can be reduced to about 17kb. Adding an additional task to the ticket for this.
> 
> Header has been implemented in Chrome Version 120.0.6 - accessibility and browser testing will be required.

@mitz-lad Complete the reach out for any branding guidance, but as agreed, we'll move this into an upcoming collection of task around redesign work.

**Comment by mitz-lad** [comment]
Created merge request with main - ready to deploy to live
