### ISSUE TITLE
Alternative Formats: Ideate changes to 'other' questions 

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#543]
## What
Ideate changes to the way we ask users for 'other' options. The current Implementation is too granular from a data collection concern, so the hypothesis is to explore the move of questions into a consolidated view with the API data requirements.

## Why
We need to support and compliment the SRA product and their data structures. 

## Done when

- [x] Ideate changes to ask for other
- [x] Describe hypothesis and assumptions
- [x] Forecast potential questions of ideation and direction, that could be used as a basis to design research activity

## Outcomes
Present back to Preference for an agreement the pattern does support their service and can be adopted by service teams, with the hypothesis tested for future iteration.

## Who needs to know about this
- @martinwake 
- @jonhurrell

**Comment by mitz-lad** [comment]
Ideated a version 2 journey and updated prototype to accompany guidance. 
Changes include:
- Updated journey
- Updated check answers page
- Content design to accommodate new journey
- Content updates to improve labels, questions and ordering of current list

Ready for catch up with Customer Preferences SRA team for acknowledgement of the updated approach. Plan to do documentation on Confluence to describe hypothesis and assumptions after the catch up with the Customer Preferences team.

**Comment by jonhurrell** [comment]
> Ideated a version 2 journey and updated prototype to accompany guidance. Changes include:
> 
> * Updated journey
> * Updated check answers page
> * Content design to accommodate new journey
> * Content updates to improve labels, questions and ordering of current list
> 
> Ready for catch up with Customer Preferences SRA team for acknowledgement of the updated approach. Plan to do documentation on Confluence to describe hypothesis and assumptions after the catch up with the Customer Preferences team.

Let's roll that documentation into the onboarding materials.
