### ISSUE TITLE
Feature: Component side navigation

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#547]
## What

Build first version of side navigation component based on prototype discussion

## Done when

Suggested Examples:

* [x] standard version (single column version /w selected indent)
* [x] standard version with sub nav (additional section)
* [x] standard version with mobile
* [x] standard version with mobile additional layout work

Deliverables:

* [x] component spec
* [x] macro component
* [x] unit tests
* [x] sass
* [x] javascript
* [x] examples
* [x] Compatibility testing evidence, including screenshots for confluence.

## Outcomes

A releasable, tested side navigation component.

## Related stories

* https://github.com/dwp/design-system/issues/176

**Comment by mitz-lad** [comment]
### Sub links list - reduce top margin
> Desktop and Mobile

I might of added this top margin on the child list of links; but looks a bit sparse. It’s currently set to `10px` can we set it to `5px` - `govuk-spacing(1)`.

![image](https://github.com/dwp/design-system/assets/72147702/05fa1556-0052-4721-880b-4ffc88406142)

**Current CSS**
```
.dwp-side-navigation__list .dwp-side-navigation__list, 
.govuk-list .dwp-side-navigation__list, 
.dwp-side-navigation__list .govuk-list, 
.govuk-list .govuk-list {
    margin-top: 10px;
}
```

---

### Links at mobile - increase hit area
> Mobile

Increase vertical padding for links to come to 1cm (approx 37px-40px). Currently the links including padding are coming around 30px-32px. Can we swap margins for padding to aid with this?

**Nav toggle**
![image](https://github.com/dwp/design-system/assets/72147702/e39b03d5-f5ef-4d71-b409-8b055f1f99e1)

**Nav link**
![image](https://github.com/dwp/design-system/assets/72147702/e88dbe17-c6d3-472b-8944-64c6f54bb28f)

---

### Focus state - hide hover underline
> Desktop and Mobile

When both the hover and focus state is triggered there is double underline

**Desktop**
![image](https://github.com/dwp/design-system/assets/72147702/86eca4dd-ebec-4713-b3a1-4a7609e4a7c4)

**Mobile**
![Screenshot 2023-11-20 at 12 14 02](https://github.com/dwp/design-system/assets/72147702/c49335b5-0f5f-46d7-9b50-f3ebed0708e6)

**Comment by htmlandbacon** [comment]
Flagged for re-review.

We've had a couple of chats around https://www.nngroup.com/articles/touch-target-size/ it might be worth when we come to do the guidance adding a bit about this.
