### ISSUE TITLE
Add cookies banner UI HTML/Nunjucks code tabs to consent to cookies documentation page

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#55]
**Is your feature request related to a problem? Please describe.**
Designers and developers will want to see the cookie banner UI code, either to copy and paste, or to get a sense of how it works. Add the code to the documentation page, using tabs to split the views between HTML and Nunjucks.

  **Describe the solution you'd like**
[Use the GDS standard approach of present associated code.](https://design-system.service.gov.uk/components/date-input/)

  **Additional context**
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by simoneduca** [comment]
On gov.uk this is built dynamically by pulling in the components' html/njk from the frontend module. I'd like to do something similar, but I understand if we want a quick win and just put the relevant files in manually. thoughts?

**Comment by simoneduca** [comment]
Preview https://add-code-examples.design-system.dwp.gov.uk/patterns/consent-to-cookies
