### ISSUE TITLE
Feature: Timeouts and casa plugin

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#550]
## What

As part of on going work we need to look at how viable splitting up coded design patterns into more functional options

## Why

Currently there is still a manual step with some of our interactive patterns for implementation, this means teams are repeatedly having to do the same thing, which means - additional work and Updates can't be easily applied.

Suggestion was to use HMRC as a trail as we know this is being used currently in a number of services

## Done when

- [x] Review of HMRC timeout component
- [x] Spec out of a casa plugin (for review)
- [x] Working casa plugin

## 0.1.0 Release activities

- [x] Add build to compile require/import
- [ ] Review test docs

## Outcomes

Outcome should be that we have a understanding (and version) of a casa plugin to allow users to easily apply timeout.

## Related stories

- https://github.com/dwp/govuk-casa
- https://design.tax.service.gov.uk/hmrc-design-patterns/service-timeout/

**Comment by htmlandbacon** [comment]
I've put this out for a couple of teams for review as a starting release.

**Comment by htmlandbacon** [comment]
I've updated our internal guidance on this, there is however a slight issue - so moving this till HMRC have released a 5.0.0 version of there work.

**Comment by jonhurrell** [comment]
Agreed to look at a full prototype journey using our pattern guidance and the HMRC component. We'll take a direction from this with regards to long term component adoption.

**Comment by htmlandbacon** [comment]
Closing - will re-open if more work comes up or we move it forward
