### ISSUE TITLE
Feature: Component add top level navigation to header

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#551]
## What

Build first version of top level navigation component based on prototype discussion.

See https://github.com/dwp/design-system/issues/513 for design.

## Done when

Suggested that two versions will be provided for this with the no-javascript version falling back to default behaviour 

* [x] standard header, adaptive to maximum header width
* [x] enhancement of Javascript version

Deliverables:

* [x] component spec
* [x] macro component
* [x] unit tests
* [x] sass
* [x] javascript
* [x] examples
* [x] Compatibility testing evidence 
* [x] Recouple components 

## Outcomes

A releasable, tested header navigation.

## Related stories

* https://github.com/dwp/design-system/issues/176
* https://github.com/dwp/design-system/issues/560

**Comment by simoneduca** [comment]
Ask @mitz-lad details on mobile view

**Comment by jonhurrell** [comment]
### Decision on decoupling header from main navigation

#### Actions

- Team agreed to couple and encapsulate the header and main navigation component together. 
- For discoverability and clarity of guidance, we'll treat them as related but separate concerns on the main site.

#### Background
If conditions or constraints on fragmented service changes we may need to separate them, to be able to offer more flexibility and widen the scope to meet those challenges. @mitz-lad Proposed the overlap between them could be easily mitigated by moving the mobile reveal within the navigation bar itself.

#### Topics covered in decision

- Discoverability on main site
- Guidance coupling vs seperation clarity
- Tracking adoption
- Encapsulation of concerns vs composition flexility (to meet those conditions mentioned above)
- Predictability of changes/maintenance with interdependency of design and engineering assets.
