### ISSUE TITLE
Onboard to Pattern Template

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#554]
## What
Teams need to be onboarding with patterns, what does that process look like and what are the handover assets

## Why
It's important we have an effective handover for the pattern adoption, to reduce support overhead and to give the teams confidence they can use the pattern in their services.

## Done when

- [x] Outline process
- [x] Produce a template that captures key knowledge transfer of pattern and any outstanding issues that may go into a research activity plan
- [ ] Document design decisions
- [ ] Package prototype for re-use 
- [ ] Guide for adding prototype to existing projects

**Comment by martinwake** [comment]
See https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133494767917/Start+here+PATTERN+NAME

**Comment by mitz-lad** [comment]
The manual process of the packaging of prototype and guide has been completed and is available [here](https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133468390824/Onboarding+Choose+alternative+contact+formats). 

There is a working version of the more automated process using npm install. The [installation guidance](https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133495718739/Choose+an+alternative+format+Install+pattern) for this is still work in progress, and is dependant on where the package will be hosted, and further testing of the end-to-end process.
