### ISSUE TITLE
Publish: How we test components and patterns

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#558]
## What
We already document how we test, so let's make that available as general guidance on the site for assurances when adopting our output.

## Why
It's important to show openly the things that go into our output so people can trust we aren't introducing any known barriers to their users.

## Done when
- [ ] Check that content on [Confluence page](https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133104665805/How+we+test+components+and+patterns) is accurate and current (@htmlandbacon / @simoneduca )
- [ ] Decide where page will live on website
- [ ] Build and publish guidance page
- [ ] Update sitemap

**Comment by htmlandbacon** [comment]
This has already been released.
