### ISSUE TITLE
Add live demo of consent to cookies to documentation and deprecate the Child Maintenance prototype

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#56]
**Is your feature request related to a problem? Please describe.**
Add our https://cookies-management.design-system.dwp.gov.uk demo link within the documentation

**Describe the solution you'd like**
Change the url to match the pattern name https://cookies-consent.design-system.dwp.gov.uk and replace the existing link to the child maintenance prototype.

 **Additional context**
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by simoneduca** [comment]
Preview of the new documentation link https://fix-56.design-system.dwp.gov.uk/patterns/consent-to-cookies#how-it-works

**Comment by simoneduca** [comment]
There is a engineering-wide issue with docker, so deploys are not working atm.
