### ISSUE TITLE
Review options for building, hosting and deploying

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#569]
## What

We should look at how we are currently building (docker), hosting (aws) and deploying (gitlab) and work out what we want to do moving forward.

## Why

If the assumption is we are moving to a static site, then how we are the running the site might not be the best way ([s3 bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html)).

We should also look at what we can do to make our deployment more robust.

We should investigate the options for each stage and decide what we want to split out as tasks/close off.

## Done when

Part 1:
- [x] Documented options for moving forward
- [x] Documented draw back of any approach
- [x] Understanding of a layered approach

Part 2:
- [x] add ourselves to account
- [x] Dummy app deployment into dev space
- [x] Deploy main site into dev space

Part 3:
- [x] Areas identified where we need support
- [x] Document questions arising from documentation
- [x] Next steps

## Outcomes

Agreed next steps, and tickets to work towards it.

## Who needs to know about this

@jonhurrell, @simoneduca, @htmlandbacon 

## Related Stories

- https://github.com/dwp/design-system/issues/566

**Comment by jonhurrell** [comment]
Let's use the disco board to highlight questions or knowledge gaps from the documentation to start to form a plan.

**Comment by jonhurrell** [comment]
We may need to start thinking about registering alternative domains like:

- design.dwp.gov.uk
- service-patterns.dwp.gov.uk
- ucd.dwp.gov.uk
