### ISSUE TITLE
Add a change-log to documentation

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#57]
**Is your feature request related to a problem? Please describe.**
People who are using the pattern will want to see what changes we've made, so there's a clearer update path for them. This will be useful for this pattern as we have already updated it based on insights coming in from services using it, but globally across the system it'd be good to read a per component/pattern change log, so we are preserving the history of changes.

  **Describe the solution you'd like**
We'll need discussion around our approach for this.

  **Additional context**
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

## Related stories
- [ ] Prototype what this could look like in context of the cookies pattern

**Comment by simoneduca** [comment]
This is interesting. I don't think we can have a changelog for each pattern/component etc. But a general changelog with specific updates about any individual component or whatever is easy. Thoughts?

**Comment by HelenOsg** [comment]
<img width="831" alt="Screen Shot 2021-01-13 at 14 16 11" src="https://user-images.githubusercontent.com/57486301/104463657-f436d400-55a9-11eb-86f3-5e44b35a0045.png">
Example of change log on GOV.UK guidance page

**Comment by jonhurrell** [comment]
Closing as duplicate of https://github.com/dwp/design-system/issues/376
