### ISSUE TITLE
Define: Design Hypothesis statements to guide design work

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#571]
## What
Capture design hypothesis to help guide the new site ideation.

## Why
We've captured a lot of functional and non functional requirements, let's pair them to some high level hypothesis to generate ideas against.

## Done when

- [x] Define a list of design hypothesis

**Comment by mitz-lad** [comment]
Initial loose hypothesis created based on the user needs and potential tasks we see people may want to do. Process of how these were determined on Mural https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1699976969544/1d753a60ccd9012263a0c95ddf3f194426788229?wid=0-1706110896094

Documented on Confluence: https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133569937746/Redesign+2024

These may require iterating and and adding to as we explore further into the design and have more team conversations.

### Hypothesis for content to include for a component or pattern  

**We believe if we include...**
- an example of component or pattern 
- when to use and when not to use
- what it doesn't do 
- brief description/intro
- responsive view of examples
**then...**
- Users will know this is the right component/pattern to use
- Users will discover what the component/pattern does
- Users will understand how the component/pattern works

 

**We believe if we include...**
- services using the component or pattern
- what was the output from accessibility testing - what it supports what it doesn't
- WCAG 2.2 considerations, recommendations
- last reviewed / next review date/time
- date/time stamp when the content was last updated
- kudos for contribution
- design history of a thing
**then...**
- users will get the assurance/confirmation they need to use the component/pattern
- users will understand the maturity level of the component/pattern


**We believe if we include..**.
- how to implement a component/pattern
- how to get DWP FE
- component composition and hierarchy 
- code examples
- content section with specific writing guidelines/considerations and general standardisation
- dependencies e.g. what components make up a pattern
- responsive view of examples
- technical history of a thing
**then...**
- users will learn how to implement the component/pattern


**We believe if we include...**
- research questions
- what was the output from accessibility testing - what it supports what it doesn't
**then...**
- users will understand the limitations of the component/pattern 


**We believe if we include...**
- how to contact us for help/support
- how to contribute
- how to report an issue
- how to share your learning
**then...**
- users will be able to tell us something about the component/pattern

 
**We believe if we include...**
- sub navigation
**then...**
- users will be able to navigate between the different sections of the page more easily
