### ISSUE TITLE
Update to Tudor crown

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#578]
## What

We need to switch to using the new Tudor crown

## Why

>If your service uses GOV.UK branding, you must update your service between 19 February and 1 March 2024 to use the new logo. You may need to update the version of GOV.UK Frontend your service uses before you can do this.

https://design-system.service.gov.uk/components/header/

## Done when

Assets are updated and deployed.

- [x] Patterns - Cookie pages
- [x] Patterns - Retired cookies banner, remove page and navigation reference
- [x] Remove Retired cookies panner from a11y test
- [x] Patterns - Contact a service - update image
- [x] Alternative formats prototype
- [x] Crown update page example needs to point to older version
- [x] Remove: This replaces the [retired Consent to cookies pattern](https://design-system.dwp.gov.uk/patterns/retired-patterns/consent-to-cookies). If your service uses the retired pattern you do not need to update it.

## To Ignore

- Pizza prototype (no branding)

## Outcomes

We have deployed the new version of the Crown.

## Who needs to know about this

@mitz-lad @claireduxs76 @simoneduca @jonhurrell @martinwake

**Comment by jonhurrell** [comment]
Retired patterns missed in the pa11y config object.
