### ISSUE TITLE
Arrange accessibility audit

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#58]
**Is your feature request related to a problem? Please describe.**
As part of assurance for any pattern we need to be making things inclusive, so we need to reach out to @abbott567 to get the cookies banner UI tested once the development is complete.

**Describe the solution you'd like**
We may have fixes or changes to make as part of the testing.

 **Additional context**
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by HelenOsg** [comment]
@jonhurrell does this need to be closed?

**Comment by jonhurrell** [comment]
@HelenOsg We can close for the cookies.
