### ISSUE TITLE
Guidance for cookie names that include unique strings

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#580]
This ticket is for the first item in #561

> Would it be possible to add some guidance for cookie names that include unique strings as part of the name? GA cookies are the main culprit. Looking through a few services, most seem to just ignore that part of the name which I think is sensible, but have seen some others have things like _gat_* 
> Noticed a couple of people asking on slack how to approach it too.
> 

_Originally posted by @paulwelsh1 in https://github.com/dwp/design-system/discussions/516#discussioncomment-7587952_

**Comment by jonhurrell** [comment]
@martinwake to get in touch with Paul to let him know outcome of his feedback.
