### ISSUE TITLE
Accessiblity example content

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#582]
## What

Flesh out a full page of accessiblity content, this should include WCAG and information about what we should and shouldn't do.

## Why

The assumption we should expose richer information abut our components from a design and technical point of view.

## Done when

- [ ] Any relevant links/examples documented on this ticket
- [x] Clear document of types of sections and purpose of each
- [x] An example of a components context

## Outcomes

We should standardise a document format, and use one of our component/patterns as an example to gather the context, this will help us better prototype the view.

We might also want to review this with the accessiblity team.

## Example content sections

| Header            | Description                                                                               | Included by default |
|-------------------|-------------------------------------------------------------------------------------------|---------------------|
| Introduction      |                                                                                           | Yes                 |
| WCAG 2.2          | Introduction to any changes that might have an impact from the WCAG 2.2 changes           | Yes                 |
| WCAG 2.1          | Introduction to main area of test focus from the component/pattern                        | Yes                 |
| - Not applied     | Outline of anything to be mindfull of in criteria we haven't applied                      | Yes                 |
| Composition       | Outline of any placement guidance for the component                                       | Yes                 |
| Useability        | Outline of do and don't for the component, if we can backup with a wcag critria we should | Yes                 |
| Notes             | Anything we've found when people have been using it                                       | No                  |
| Testing           | Any strict criteria we can document to go with the component                              | No                  |
| Technical options | Subset of the macro options                                                               | Yes                 |

## Anything else

- We should also consider panels to set context of other things, like https://neurodiversity.design/ where applied.

**Comment by jonhurrell** [comment]
Should we include a specific heading around Neurodiversity, to bring that content and guidance out?
https://neurodiversity.design

**Comment by martinwake** [comment]
> Should we include a specific heading around Neurodiversity, to bring that content and guidance out? https://neurodiversity.design

Not sure but if so I think that also implies specific sections for eg visual impairment, cognitive difficulty, motor skills; there might be a lot of repetition from other sections

**Comment by jonhurrell** [comment]
Content bucket paradigm solves that problem. Pulling it out, gives it the prominence for consideration.

**Comment by htmlandbacon** [comment]
I'm closing this as the core of the task is done!
