### ISSUE TITLE
Add addtional key details examples

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#586]
## What

We should review and add additional example to key details

## Why

Our only two examples are largely the same with a different tag, the assumption is giving richer examples might be useful.

## Done when

- [ ] Update main example to be without tag
- [ ] Add example of slim item
- [ ] Check third item standard tag

## Outcomes

Release to be made

**Comment by jonhurrell** [comment]
@martinwake It was suggested we may need to make the basic component example content more agnostic against the intent, e.g.: Customer name, should be expressed closer to 'primary identifier' (e.g: customer name or record ID).
Then the examples would set the context for using the bar for identifying by person.

**Comment by martinwake** [comment]
> @martinwake It was suggested we may need to make the basic component example content more agnostic against the intent, e.g.: Customer name, should be expressed closer to 'primary identifier' (e.g: customer name or record ID). Then the examples would set the context for using the bar for identifying by person.

How about this?
![image](https://github.com/dwp/design-system/assets/26182217/122554b6-7e5b-4732-bf60-519859e30dc7)
