### ISSUE TITLE
Improvement: Update alternative formats prototype to reflect PEN research and SRA component

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#587]
## Context
When we have the list of formats available in the Citizen Preference Service we should update the prototype in the alternative formats pattern to be consistent with it.

We should also update the prototype to reflect insights from the PEN team research as documented on the "Proposed changes" page in Confluence.

## Decision
Should we remove formats that are not available, or just make sure that all the formats that are available are represented and consistent?

**Comment by jonhurrell** [comment]
Duplicate.
