### ISSUE TITLE
Feature: Component horizontal navigation 

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#593]
## What

Review and spec out first version of 'horizontal sub navigation' navigation component for discussion.

## Why

We've seen a number of services using sub navigation (in page navigation) along side header navigation to navigate there service

## Done when

First thing we need review what we have and pick a version to take forward

* [x] component spec
* [x] macro component
* [x] unit tests
* [x] sass
* [x] javascript -(to be reviewed)
* [x] examples
* [x] Compatibility testing evidence 

Following review the following use cases need to be applied:

* [x] Additional stacking for mobile
* [x] JavaScript menu item applied as optional component (review against side navigation and menu item)

## Outcomes

A releasable, tested internal service sub navigation.

Review component against others and decide what we might want to extract as a ticket.

Follow up ticket to update guidance on main site.

## Related stories

- https://github.com/dwp/design-system/issues/497

**Comment by htmlandbacon** [comment]
Review session schedule before testing

**Comment by htmlandbacon** [comment]
When going through this I noticed a couple of parts of the code are now starting to repeat: we might want to consider extracting these out for maintenance/utility reasons.

I've added this as an outcome.

**Comment by htmlandbacon** [comment]
From my point of view this is as done as its going to be - will pick up how we are going to release etc later this week.

**Comment by htmlandbacon** [comment]
To update:

* [x] Double check and update design branch with mobile version
* [x] Review and take design layouts into developer branch
* [x] Confirm additional spacing on mobile version
* [x] Confirm additional spacing on bottom of the component

To remove to second version branch:

* [x] Use as header navigation companion
* [x] Mobile menu functionally

**Comment by mitz-lad** [comment]
Reviewed preview site found an issue with mobile link width. 

![Image](https://github.com/user-attachments/assets/856faf4e-05cb-4684-80ab-743abd6e7b02)

This has been noted to address for mobile and tablet views. All other behaviour and styles as expected for this iteration.

**Comment by htmlandbacon** [comment]
Will pick up when we do compatibility testing!

**Comment by htmlandbacon** [comment]
Got a developer review of this with the wider community on Monday the 13th
