### ISSUE TITLE
Update Alternative formats prototype following PEN findings

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#602]
## What
Update the Alternative formats example prototype to reflect findings from research by the PEN team.

## Why
There are several insights that we should adopt into our example service.

## Done when

- [x] Remove separate large print option and consolidate into second option
- [x] Rewrite Textphone label and hint text
- [x] Update Check answers headings from "when" to "how"

Details are on "Proposed changes" page in Confluence documentation

## Outcomes
Prototype is updated

## Who needs to know about this
Design System team
PEN team

**Comment by jonhurrell** [comment]
@martinwake https://dwp-design-system-examples-c0557c2c3d1d.herokuapp.com/examples/alternative-formats/v2/journey-1/index

**Comment by jonhurrell** [comment]
@martinwake to contact PEN team with changes and diversions.
