### ISSUE TITLE
feature: build out "quick reference" Component

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#609]
## What

Build first version of quick reference based on design review.

First pass to include element based on the basic https://design-system.dwp.gov.uk/components/key-details-bar/

## Where have we seen this

- Winter fuel
- Retirement Agent

## Done when

Suggested Versions:

* [x] First pass at single version using primaryIdentifier, secondaryIdentifier and status.
* [x] background colour/border version
* [ ] ~additional slot version~ - decided to not to this

Developer Deliverables:

* [x] component spec
* [x] macro component
* [x] unit tests
* [x] sass
* [x] examples with variation text types
* [x] examples in layout
* [x] Compatibility testing evidence, including screenshots for confluence.

## Outcomes

A releasable, tested side Unnamed Component.

**Comment by htmlandbacon** [comment]
Assumption is this will be done in three stages:

1. Developer pass
2. Examples generated with designers
3. Testing

**Comment by mitz-lad** [comment]
Modified first pass with design amends to spacing and typography scaling. 

Repo: https://gitlab.com/dwp/dwp-design-system/dwp-frontend/-/tree/f-609-design?ref_type=heads

**Comment by htmlandbacon** [comment]
Put this out for design review with a version 2.8.0-rc.1310653291

**Comment by htmlandbacon** [comment]
From my point of view this is as done as its going to be, it still needs merging but will pick up how we are going to release etc later this week.

**Comment by htmlandbacon** [comment]
Released as part of [2.8.0](https://www.npmjs.com/package/@dwp/dwp-frontend/v/2.8.0)
