### ISSUE TITLE
Publish draft Quick reference guidance

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#615]
## What
Publish draft guidance for the Quick reference component for preview period.

## Why
The new component needs guidance on how to use it.

## Done when

- [x] Composition examples built and added to page (@mitz-lad)
- [x] Layout examples published on separate page (@htmlandbacon / @mitz-lad )
- [x] Guidance updated to refer to correct examples
- [x] Nav items etc updated to include new component
- [x] pa11y and playwright tests updated (@htmlandbacon )
- [x] Guidance published

## Outcomes
 - [x] Guidance is published

## Who needs to know about this

Design System team
Interaction Design community
Content design community
Front end devs

**Comment by jonhurrell** [comment]
[Published](https://design-system.dwp.gov.uk/components/quick-reference)
