### ISSUE TITLE
Filters: Scope for iteration

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#631]
## What
Define what problems we plan to solve in version 1 of the filters component.

## Why
To define what design work will focus on and make it clear in our documentation and guidance what we have addressed and what we haven't.

## Done when

- [x] Gather issues, problems and questions
- [x] Discuss with team what we have found
- [x] Choose which we should focus on for this iteration

## Outcomes
- A clear definition of questions and design elements we will address in the design phase

## Who needs to know about this
Design system team

**Comment by mitz-lad** [comment]
Formulated initial hypothesis and decisions setup meeting with team to review, add, amend and decide which to take forward into design.

**Comment by jonhurrell** [comment]
Assigned to review (@mitz-lad post link in slack).

**Comment by mitz-lad** [comment]
Reviewed filters research and hypotheses and scope with team. Documented: 
- [Context and intent](https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133707858093/Filters)
- [Considerations and hypothesis](https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133707858231/Design+-+Filters)
