### ISSUE TITLE
File upload: Desk research

### ISSUE THREAD

**Issue by claireduxs76** [dwp/design-system#633]
## What
Gathering insights into how services in DWP are using the file upload component. This will allow us to compare to UC's version so we can identify if/where opportunties exist to enhance and create a DWP file upload component
## Why
Services use different methods for file uploads, which can lead to inconsistency. Establishing a set of principles for file upload usage, along with a standard component, will make it easier for designers to implement and customise file uploads for their users efficiently and consistently.

## Done when

- [ ] Gather examples and insights from DWP services
- [ ] Gather examples from UC 
- [ ] Desk research to establish areas of concerns and considerations

## Outcomes
Findings to guide how to proceed

## Who needs to know about this
Design System Team

**Comment by claireduxs76** [comment]
Started gathering examples and areas of concern on Mural: https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1721919063004/6710429d7db822dbcfe12b90b5b5ce56de6e5422?sender=ubb27d5a896d0c3d19d875317

**Comment by jonhurrell** [comment]
@claireduxs76 to setup review meet for effort scoping.

**Comment by jonhurrell** [comment]
Next step is to arrange a workshop with UC to cover any differences/improvements, to agree if the existing pattern can be replaced (in prototype context).

**Comment by jonhurrell** [comment]
Moved to ideate using desk research as a basis. Replay back to UC after this stage to cover off commonality/difference between their existing pattern and the wider one we'll produce.
