### ISSUE TITLE
Implement Engineering resources tagging policy

### ISSUE THREAD

**Issue by simoneduca** [dwp/design-system#637]
**What**

The main-site architecture doesn't comply with the new tagging policy

**Done when**

- [ ] Service request to add design system to applications list
- [x] add tags to resources in infrastructure template

**Comment by simoneduca** [comment]
Our team can't access the right DWP Place form to complete this ticket. I've opened incident INC9462194 about that but it was no use. I've asked David for help and waiting for him to get back to us.

**Comment by htmlandbacon** [comment]
Our re-worked tagging has been sent for review on the 4th of September.

Put this in review but appreciate there is two work flows for the tasks on here

**Comment by htmlandbacon** [comment]
Based on what we have been given feedback on this is done and released.

We'll request another report, and open up any follow up tasks based on that.
