### ISSUE TITLE
Cookies banner persists in IE11

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#83]
**Describe the bug**
The cookies banner persists once an option has been selected and navigated away.

**To Reproduce**
1. Go to BowserStack, IE11 'https://design-system.dwp.gov.uk/index'
2. Click on 'Yes, I accept cookies', then change option link in banner
3. See error
4. Console log reports 'includes' prop or method not supported

**Expected behavior**
Banner hides once an option is selected and hide selected, or option selected and navigated away

**Additional context**
Check IE method/property polyfill is imported.

**Comment by simoneduca** [comment]
Sorted.
